services:
  nyk-credit-score:
    container_name: nyk-credit-score
    build:
      context: ./credit-score-service
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - SERVICE_NAME=NYKCS
      - PORT=3000
    networks:
      - credit-score-network
  bkn-credit-score:
    container_name: bkn-credit-score
    build:
      context: ./credit-score-service
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment:
      - SERVICE_NAME=BKNCS
      - PORT=3001
    networks:
      - credit-score-network
  credit-score-gateway:
    container_name: credit-score-gateway
    build:
      context: ./credit-score-gateway
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
    environment:
      - CSG_HTTP_PORT=8080
      - CSG_TCP_PORT=8081
      - CSG_GRPC_PORT=8082
      - CSG_NYKCS_SERVICE_NAME=NYKCS
      - CSG_NYKCS_BASE_URL=http://nyk-credit-score:3000
      - CSG_NYKCS_TIMEOUT_MILLIS=250
      - CSG_BKNCS_SERVICE_NAME=BKNCS
      - CSG_BKNCS_BASE_URL=http://bkn-credit-score:3001
      - CSG_BKNCS_TIMEOUT_MILLIS=250
    networks:
      - credit-score-network

networks:
  credit-score-network:
    driver: bridge
